branches:
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/github'
    - assets:
      - deb-*/*.deb
  - - '@semantic-release/git'
    - assets:
      - CHANGELOG.md
      - Cargo.toml
      - Cargo.lock
      message: "chore(release): set `Cargo.toml` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
