[target.arm-unknown-linux-gnueabihf.dockerfile]
file = "./cross-rs/Dockerfile.armhf"
context = "./cross-rs/"

[target.aarch64-unknown-linux-gnu.dockerfile]
file = "./cross-rs/Dockerfile.aarch64"
context = "./cross-rs/"
